export const userRights = [
  { field: 'view_reports', label: 'View Reports' },
  { field: 'alter_agent_interface_options', label: 'Alter Agent Interface Options' },
  { field: 'modify_users', label: 'Modify Users' },
  { field: 'change_agent_campaign', label: 'Change Agent Campaign' },
  { field: 'delete_users', label: 'Delete Users' },
  { field: 'modify_usergroups', label: 'Modify User Groups' },
  { field: 'delete_user_groups', label: 'Delete User Groups' },
  { field: 'modify_lists', label: 'Modify Lists' },
  { field: 'delete_lists', label: 'Delete Lists' },
  { field: 'load_leads', label: 'Load Leads' },
  { field: 'modify_leads', label: 'Modify Leads' },
  { field: 'export_gdpr_leads', label: 'GDPR-Compliant Export Delete Leads' },
  { field: 'download_lists', label: 'Download Lists' },
  { field: 'export_reports', label: 'Export Reports' },
  { field: 'delete_from_dnc', label: 'Delete From DNC Lists' },
  { field: 'modify_campaigns', label: 'Modify Campaigns' },
  { field: 'campaign_detail', label: 'Campaign Detail' },
  { field: 'modify_dial_prefix', label: 'Modify Campaign Dial Prefix' },
  { field: 'delete_campaigns', label: 'Delete Campaigns' },
  { field: 'modify_ingroups', label: 'Modify In-Groups' },
  { field: 'delete_ingroups', label: 'Delete In-Groups' },
  { field: 'modify_inbound_dids', label: 'Modify DIDs' },
  { field: 'delete_inbound_dids', label: 'Delete DIDs' },
  { field: 'modify_custom_dialplans', label: 'Modify Custom Dialplans' },
  { field: 'modify_remoteagents', label: 'Modify Remote Agents' },
  { field: 'delete_remote_agents', label: 'Delete Remote Agents' },
  { field: 'modify_scripts', label: 'Modify Scripts' },
  { field: 'delete_scripts', label: 'Delete Scripts' },
  { field: 'modify_filters', label: 'Modify Filters' },
  { field: 'delete_filters', label: 'Delete Filters' },
  { field: 'ast_admin_access', label: 'AGC Admin Access' },
  { field: 'ast_delete_phones', label: 'AGC Delete Phones' },
  { field: 'modify_call_times', label: 'Modify Call Times' },
  { field: 'delete_call_times', label: 'Delete Call Times' },
  { field: 'modify_servers', label: 'Modify Servers' },
  { field: 'modify_shifts', label: 'Modify Shifts' },
  { field: 'modify_phones', label: 'Modify Phones' },
  { field: 'modify_carriers', label: 'Modify Carriers' },
  { field: 'modify_labels', label: 'Modify Labels' },
  { field: 'modify_colors', label: 'Modify Colors' },
  { field: 'modify_statuses', label: 'Modify Statuses' },
  { field: 'modify_voicemail', label: 'Modify Voicemail' },
  { field: 'modify_audiostore', label: 'Modify Audio Store' },
  { field: 'modify_moh', label: 'Modify Music On Hold' },
  { field: 'modify_tts', label: 'Modify TTS' },
  { field: 'modify_contacts', label: 'Modify Contacts' },
  { field: 'callcard_admin', label: 'CallCard Access' },
  { field: 'add_timeclock_log', label: 'Add Timeclock Log Record' },
  { field: 'modify_timeclock_log', label: 'Modify Timeclock Log Record' },
  { field: 'delete_timeclock_log', label: 'Delete Timeclock Log Record' },
  { field: 'manager_shift_enforcement_override', label: 'Manager Shift Enforcement Override' },
  { field: 'pause_code_approval', label: 'Pause Code Approval' },
  { field: 'modify_same_user_level', label: 'Modify Same User Level' },
  { field: 'admin_hide_lead_data', label: 'Admin Hide Lead Data' },
  { field: 'admin_hide_phone_data', label: 'Admin Hide Phone Data' },
  { field: 'agentcall_email', label: 'Agent Call Email' },
  { field: 'modify_email_accounts', label: 'Modify Email Accounts' },
  { field: 'alter_admin_interface_options', label: 'Alter Admin Interface Options' },
  { field: 'modify_languages', label: 'Modify Languages' },
  { field: 'user_choose_language', label: 'User Choose Language' },
  { field: 'ignore_group_on_search', label: 'Ignore Group on Search' },
  { field: 'api_only_user', label: 'API Only User' },
  { field: 'modify_auto_reports', label: 'Modify Auto Reports' },
  { field: 'modify_ip_lists', label: 'Modify IP Lists' },
  { field: 'ignore_ip_list', label: 'Ignore IP List' },
  { field: 'mute_recordings', label: 'Mute Recordings' },
  { field: 'hide_call_log_info', label: 'Hide Call Log Info' },
  { field: 'next_dial_my_callbacks', label: 'Next Dial My Callbacks' },
  { field: 'max_inbound_filter_enabled', label: 'Max Inbound Filter Enabled' },
  { field: 'hci_enabled', label: 'HCI Enabled' },
  { field: 'manual_dial_lead_id', label: 'Manual Dial Lead ID' },
];