const mockClients = [
{
  id: 1,
  nom: "hannibal",
  prenom: "Groupe",
  societe: "hannibal",
  email: "a.hannibal@hannibal.fr",
  telephone: "+33 6 12 34 56 99",
  statut: "client_actif",
  solde: 50.50,
  date_creation: "2025-03-12",
  plan: {
    type: "pro",
    frequence: "annuel",
    utilisateurs: 25
  },
  pays: "France",
},
  {
    id: 2,
    nom: "Tounsi",
    prenom: "Ahmed",
    societe: "Tounsi",
    email: "a.tounsi@tounsi.fr",
    telephone: "+33 6 12 34 56 78",
    statut: "client_actif",
    solde: 250.50,
    date_creation: "2026-03-12",
    plan: { type: "pro", frequence: "annuel", utilisateurs: 25 },
    pays: "France",
  },
  {
    id: 3,
    nom: "Kefi",
    prenom: "Ali",
    societe: "Scte Kefi",
    email: "kefi@kefi.tn",
    telephone: "+216 73 123 405",
    statut: "prospect",
    solde: 150.50,
    date_creation: "2025-03-13",
    plan: { type: "essentiel", frequence: "mensuel", utilisateurs: 5 },
    pays: "Tunisie",
  },
  {
    id: 4,
    nom: "Karoui",
    prenom: "Ahmed",
    societe: "Scte Karoui",
    email: "karoui@karoui.tn",
    telephone: "+216 73 001 456",
    statut: "client_actif",
    solde: 2250.50,
    date_creation: "2025-04-10",
    plan: { type: "pro", frequence: "annuel", utilisateurs: 50 },
    pays: "Tunisie",
  },
  {
    id: 5,
    nom: "Ben mohamed",
    prenom: "Mohamed",
    societe: "Scte Ben mohamed",
    email: "benmohamed@benmohamed.tn",
    telephone: "+33 7 13 20 11 45",
    statut: "suspendu",
    solde: 3050.50,
    date_creation: "2025-02-10",
    plan: { type: "avance", frequence: "mensuel", utilisateurs: 15 },
    pays: "France",
  },
  {
    id: 6,
    nom: "Benzarti",
    prenom: "Samira",
    societe: "Scte Benzarti",
    email: "benzarti@benzarti.tn",
    telephone: "+216 77 001 456",
    statut: "prospect",
    solde: 1151.00,
    date_creation: "2025-04-13",
    plan: { type: "essentiel", frequence: "mensuel", utilisateurs: 3 },
    pays: "Tunisie",
  },
  {
    id: 7,
    nom: "Ben Hammouda",
    prenom: "Ahmed",
    societe: "Scte Ben Hammouda",
    email: "benhhammouda@benhhammouda.tn",
    telephone: "+216 73 001 211",
    statut: "resilie",
    solde: 350.50,
    date_creation: "2025-02-14",
    plan: { type: "essentiel", frequence: "mensuel", utilisateurs: 8 },
    pays: "Tunisie",
  },
  {
    id: 8,
    nom: "Jouini",
    prenom: "Karim",
    societe: "Karim Jouini",
    email: "jouini@jouini.tn",
    telephone: "+216 77 001 256",
    statut: "client_actif",
    solde: 50.50,
    date_creation: "2025-01-10",
    plan: { type: "pro", frequence: "annuel", utilisateurs: 25 },
    pays: "Tunisie",
  },
  {
    id: 9,
    nom: "Hatab",
    prenom: "Ahmed",
    societe: "Scte Hatab",
    email: "hatab@hatab.tn",
    telephone: "+33 7 00 21 45 36",
    statut: "client_actif",
    solde: 200.50,
    date_creation: "2025-01-10",
    plan: { type: "avance", frequence: "annuel", utilisateurs: 20 },
    pays: "France",
  },
  {
    id: 10,
    nom: "Asli",
    prenom: "Mariem",
    societe: "M.Asli",
    email: "asli@asli.tn",
    telephone: "+216 73 001 000",
    statut: "suspendu",
    solde: 150.50,
    date_creation: "2025-04-10",
    plan: { type: "essentiel", frequence: "mensuel", utilisateurs: 4 },
    pays: "Tunisie",
  },
  {
    id: 11,
    nom: "Kallel",
    prenom: "Ahmed",
    societe: "Scte Kallel",
    email: "kallel@kallel.tn",
    telephone: "+216 73 001 203",
    statut: "client_actif",
    solde: 125.50,
    date_creation: "2025-04-10",
    plan: { type: "pro", frequence: "mensuel", utilisateurs: 10 },
    pays: "Tunisie",
  },
  {
    id: 12,
    nom: "Ben Saleh",
    prenom: "Saleh",
    societe: "Scte Ben Saleh",
    email: "bensaleh@bensaleh.tn",
    telephone: "+33 6 00 31 20 23",
    statut: "resilie",
    solde: 50.50,
    date_creation: "2025-04-11",
    plan: { type: "essentiel", frequence: "mensuel", utilisateurs: 6 },
    pays: "France",
  },
  {
    id: 13,
    nom: "Ben Janet",
    prenom: "Khalif",
    societe: "Scte Ben Janet",
    email: "benjanet@benjanet.tn",
    telephone: "+216 73 201 213",
    statut: "resilie",
    solde: 1050.50,
    date_creation: "2025-05-15",
    plan: { type: "avance", frequence: "annuel", utilisateurs: 12 },
    pays: "Tunisie",
  },
  {
    id: 14,
    nom: "Soltani",
    prenom: "Hamida",
    societe: "Scte Soltani",
    email: "soltani@soltani.tn",
    telephone: "+216 73 111 203",
    statut: "prospect",
    solde: 140.50,
    date_creation: "2025-01-10",
    plan: { type: "essentiel", frequence: "mensuel", utilisateurs: 2 },
    pays: "Tunisie",
  },
];
export const getClients = async () => {
  // Plus tard : return axios.get('/api/clients')
  return new Promise((resolve) => {
    setTimeout(() => resolve(mockClients), 300);
  });
};